### ISSUE TITLE
Feature request: option to provide server path to fonts

### ISSUE THREAD

**Issue by jugglingcats** [dzhuang/subset-iconfont#117]
Thanks a lot for this project!

I am integrating into vite/React project and want to put my CSS in one place and fonts in another, so fonts will be located in `/fonts/xxxxx.woff2` during build. The CSS that is generated currently references font files using `../webfonts/xxxxx.woff2`. It would be good to have an option to specify the relative (or server-relative) path, for example:

```
const mdi = new MiProvider(['comment'], {
    formats: ['ttf', 'woff2'],
    generateMinCss: false,
    writeOutFiles: ['webfonts', 'css'],
    cssChoices: [],
    webfontServerPath: "/fonts" // default '../webfonts'
    prefix
});
```

**Comment by dzhuang** [comment]
Thanks for the request. I am wondering if a change to [webfontdir ](https://github.com/dzhuang/subset-iconfont#webfontdir) suffient for your purpose?

**Comment by dzhuang** [comment]
That sounds great. Thank you for your response, and I am now closing this issue.
