### ISSUE TITLE
Using Google Material Icons 'nice name' instead of code point.

### ISSUE THREAD

**Issue by bwownbwead** [dzhuang/subset-iconfont#387]
Hello.

Just wondering if there's any way to use the nice name for google material icons, instead of the code point?

![image](https://github.com/dzhuang/subset-iconfont/assets/6230887/79e1ca64-1ef3-42bf-94c6-4abb0b474b49)

So, using "verified_user" instead of "e8e8" to output the icon.

Sorry, I'm not too familiar with the anatomy of a font file.

Many thanks!

**Comment by dzhuang** [comment]
Actually we were using the nice names. See demo in https://github.com/dzhuang/subset-iconfont/blob/1c3b5ef2814e1f59050b51e373007cf0e176db69/src/demo-standalone.js#L39-L51
I think you can replace `'add-circle'` with the names you like.

**Comment by bwownbwead** [comment]
Thanks for the speedy reply. 

Regarding the nice names, I'm referring to the output rather than the input/config.

For example, if you were to use Google Material Icons directly from Google using their original font then you can insert an icon using a span and a 'nice name'.

Like here: https://fonts.google.com/icons?selected=Material+Icons:account_circle:&icon.set=Material+Icons&icon.style=Filled, you can insert the home icon using:

<img width="315" alt="Screenshot 2023-12-07 at 10 27 28" src="https://github.com/dzhuang/subset-iconfont/assets/6230887/32486242-972e-4266-9cd3-2bd8a17136c2">

But when using the subset font generated by your package, this seems to stop working and the only way of manually inserting an icon is to use the code point:

<img width="315" alt="image" src="https://github.com/dzhuang/subset-iconfont/assets/6230887/e242129a-a67a-4f10-a454-e7bbf3e715e0">

`<span class="material-icons">&#e88a;</span>`.

Oh and by the way, I'm using your package just to get the font-file to be used in another context. So I'm not using any of the CSS/SCSS provided by the package.

Thanks for your work and replies.

**Comment by dzhuang** [comment]
Thank you for elaborating on your issue.

The behavior you're experiencing with the package is indeed expected. Our package, like Google Material Icons, uses font icons, which require specific code points to render the icons correctly. When you use the original Google Material Icons directly from Google, they allow the use of 'nice names' as part of their implementation, which under the hood gets translated to the respective code points.

However, in the case of our package, we rely on these code points directly for rendering icons. This is why you need to use the specific character reference (like &#e88a; for the home icon) in your span class. The 'nice names' approach is not supported in our current implementation.

Regarding the CSS/SCSS files, even though you're not using them directly in your project, they are crucial for proper rendering of the icons. These stylesheets define the necessary font-family and other properties required for the icons to display correctly using the code points. Hence, to use the icons from our package, it's essential to include and reference the generated CSS.

I hope this clarifies the situation. If you have any more questions or need further assistance, feel free to reach out.

Thanks for using our package, and I appreciate your feedback!

Best regards.

**Comment by bwownbwead** [comment]
Yes, thank you very much.
