### ISSUE TITLE
Some icons are not added with MiProvider

### ISSUE THREAD

**Issue by A-tG** [dzhuang/subset-iconfont#388]
For example 'add-circle' outline variant is not added:
```js
import { MiProvider} from 'subset-iconfont';

const mi = new MiProvider([
  'pause-circle', 
  'play-circle', 
  'settings', 
  'light-mode', 
  'dark-mode', 
  'expand-less', 
  'add-box',
  'add-circle',
  'remove-circle',
  'close',
  'check-box-outline-blank',
  'check-box',
  'star'
  ], {
  formats: ['ttf', 'woff', 'woff2'],
});

mi.makeFonts('./font-output').then((result) => {
  console.log('Done!');
});
```
![image](https://github.com/dzhuang/subset-iconfont/assets/19589064/fff1ef2d-a1d8-4025-b060-3e5bcb48a03c)

and there is icon from google site https://fonts.google.com/icons?icon.query=add_circle

**Comment by dzhuang** [comment]
I think you can try this `add-circle-outline`, see the [source](https://github.com/marella/material-icons/blob/9b6cb00bf8c1627ed65b6a78149df7abae14e144/css/material-icons.css#L442).

**Comment by A-tG** [comment]
Yeah, it works
